// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ACE Agent configuration
 */
export type AceConfig = { fast_model_id: string, reflector_model_id: string, curator_model_id: string, };
