// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application configuration
 */
export type AppConfig = { theme: string, language: string, font_size: number, auto_save: boolean, notifications: boolean, active_model_id: string | null, active_provider_id: string | null, };
