// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AceConfig } from "./AceConfig";
import type { AppConfig } from "./app_config";
import type { ChatSession } from "./ChatSession";
import type { LLMModel } from "./LLMModel";
import type { LLMProvider } from "./LLMProvider";
import type { McpServer } from "./McpServer";

/**
 * Main application state
 */
export type AppState = { config: AppConfig, sessions: { [key in string]?: ChatSession }, current_session_id: string | null, providers: Array<LLMProvider>, models: Array<LLMModel>, mcp_servers: Array<McpServer>, ace_config: AceConfig, theme: string, language: string, };
