// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM Model configuration
 */
export type LLMModel = { id: string, provider_id: string, name: string, model_id: string, model_type: string, context_length: number | null, max_tokens: number | null, temperature: number | null, dimensions: number | null, is_default: boolean, };
