// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MCP Server configuration
 */
export type McpServer = { id: string, server_type: string, command: string, args: Array<string>, env: { [key in string]?: string }, };
