// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chat message structure
 */
export type Message = { id: string, role: string, content: string, timestamp: number, model_id: string | null, attachments: Array<string>, images: Array<string>, };
