// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * Chat session/conversation
 */
export type ChatSession = { id: string, title: string, messages: Array<Message>, created_at: bigint, updated_at: bigint, model_id: string | null, };
