// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM Provider configuration
 */
export type LLMProvider = { id: string, name: string, provider_type: string, base_url: string, api_key: string, enabled: boolean, };
