// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LegacyAppConfig = { theme: string, language: string, active_model: string, provider: string, };
